#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Remove a docker instance
#?? 1.0.0
##?
##? Usage:
##?    rm

docs::eval "$@"

if docker ps >/dev/null 2>&1; then

  container=$( docker ps -a | 
  		awk '{
  			if(NR==1){
  			 print "all: Remove all containers"
  			}else{
  			 print $1 ": " $(NF)
  			}
  		    }' |
  		fzf --height 40%
  	    )

  if [[ -n $container ]]; then
    container_id=$(echo $container | awk -F ': ' '{print $1}')
    if [ $container_id == "all" ]; then
	echo "First stop the containers"
    	docker stop $(docker ps -a -q)
    	echo "Removing all the containers"
	docker rm $(docker ps -a -q)
    else
       docker stop $container_id
       docker rm $container_id
    fi
  else
    echo "You haven't selected any container! ༼つ◕_◕༽つ"
  fi
else
  echo "Docker daemon is not running! (ಠ_ಠ)"
fi
